# 100.times do 
#   user = User.create(name: FFaker::Name.name, title: FFaker::Company.position, email: FFaker::Internet.email)
# end

# new = Follow.create(follower_id: 1, leader_id: 3)
# new = Follow.create(follower_id: 1, leader_id: 5)
# new = Follow.create(follower_id: 1, leader_id: 7)
# new = Follow.create(follower_id: 1, leader_id: 9)
# new = Follow.create(follower_id: 2, leader_id: 4)
# new = Follow.create(follower_id: 2, leader_id: 6)
# new = Follow.create(follower_id: 2, leader_id: 8)
# new = Follow.create(follower_id: 2, leader_id: 10)
# new = Follow.create(follower_id: 3, leader_id: 1)
# new = Follow.create(follower_id: 3, leader_id: 2)
# new = Follow.create(follower_id: 3, leader_id: 3)
# new = Follow.create(follower_id: 3, leader_id: 5)
# new = Follow.create(follower_id: 3, leader_id: 7)
# new = Follow.create(follower_id: 3, leader_id: 9)

new = Follow.create(follower_id: 1, leader_id: 101)
new = Follow.create(follower_id: 2, leader_id: 101)
new = Follow.create(follower_id: 3, leader_id: 101)
new = Follow.create(follower_id: 4, leader_id: 101)
new = Follow.create(follower_id: 5, leader_id: 101)
new = Follow.create(follower_id: 6, leader_id: 101)
new = Follow.create(follower_id: 7, leader_id: 101)
new = Follow.create(follower_id: 8, leader_id: 101)
new = Follow.create(follower_id: 9, leader_id: 101)
new = Follow.create(follower_id: 10, leader_id: 101)
new = Follow.create(follower_id: 11, leader_id: 101)
new = Follow.create(follower_id: 12, leader_id: 101)
new = Follow.create(follower_id: 13, leader_id: 101)
new = Follow.create(follower_id: 14, leader_id: 101)
new = Follow.create(follower_id: 15, leader_id: 101)
new = Follow.create(follower_id: 16, leader_id: 101)
new = Follow.create(follower_id: 17, leader_id: 101)
new = Follow.create(follower_id: 18, leader_id: 101)
new = Follow.create(follower_id: 19, leader_id: 101)
new = Follow.create(follower_id: 20, leader_id: 101)
